/**
 * Pre-bundle step: compile + bundle each plugin's TypeScript into a single ESM
 * string that the Worker Loader can run at runtime (no build step exists inside
 * workerd). `cloudflare:workers` is kept external — the runtime provides it.
 *
 * Run with: bun run build:plugins
 */
const PLUGINS = [
  {
    entry: "src/plugins/echo-plugin.ts",
    out: "src/plugins/echo-plugin.bundle.ts",
    constName: "ECHO_PLUGIN_BUNDLE",
  },
];

for (const plugin of PLUGINS) {
  const result = await Bun.build({
    entrypoints: [plugin.entry],
    target: "browser",
    format: "esm",
    external: ["cloudflare:workers"],
  });

  if (!result.success) {
    console.error(result.logs);
    process.exit(1);
  }

  const code = await result.outputs[0]!.text();
  const file = `// GENERATED by scripts/build-plugins.ts — do not edit by hand.\nexport const ${plugin.constName} = ${JSON.stringify(code)};\n`;
  await Bun.write(plugin.out, file);
  console.log(`bundled ${plugin.entry} -> ${plugin.out} (${code.length} bytes)`);
}
